config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match ':controller(/:action(:/id))', :via => [:get, :post]
  
  resource :food
  resources :users do
    resources :goals
  end

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/food.rb
class Food < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2 }
  validates :cal, presence: true
  belongs_to :user
end

app/models/goal.rb
class Goal < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  
  has_many :food
  has_one :goal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to :root
    else
      redirect_to :root, flash: { error: @food.errors.full_messages }
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to :root
  end

  private
    def food_params
      food_params = params[:food]
      food_params[:cal] = MathStringParserService.run(food_params[:cal])
      food_params[:protein] = MathStringParserService.run(food_params[:protein]) || 0
      food_params[:carbohydrates] = MathStringParserService.run(food_params[:carbohydrates]) || 0
      food_params[:fat] = MathStringParserService.run(food_params[:fat]) || 0
      params.require(:food).permit(:name, :cal, :protein, :carbohydrates, :fat, :user_id)
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def create
      @goal = Goal.new(goal_params)
      @goal.save
      redirect_to :root
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update_attributes(goal_params)
    redirect_to :root
  end

  def destroy
      @goal = Goal.joins(params[:id])
      @goal.destroy
      redirect_to :root
  end

  private
    def goal_params
        params.require(:goal).permit(:cal, :protein, :carbohydrates, :fat)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @foods = Food.where(:user_id => uid)
    @goal = Goal.find_or_create_by(:user_id => uid) 
  end

  private
    def uid
      current_user.id
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper

    def no_food?(foods)
        return foods.empty?
    end
    
    # TODO: needs to be more DRY
    def total_calories(foods)
        foods.inject(0) { |sum,food| sum + food.cal }
    end

    def format_protein(foods, goal)
        "#{foods.inject(0) { |sum,food| sum + food.protein }}/#{goal.protein}"
    end

    def format_carbs(foods, goal)
        "#{foods.inject(0) { |sum,food| sum + food.carbohydrates }}/#{goal.carbohydrates}"
    end

    def format_fat(foods, goal)
        "#{foods.inject(0) { |sum,food| sum + food.fat }}/#{goal.fat}"
    end

    def calories_left(foods, goal)
        calories = goal.cal || 2400
        calories - total_calories(foods)
    end

    def protein_left(foods, goal)
      calories = goal.cal || 2400
      calories - total_calories(foods)
    end

    def titleize(str)
        str.split(" ").map{|word| word.capitalize}.join(" ")
    end
end

app/views/foods/_form.html.erb
<%= form_for :food, url: {action: 'create', controller: 'foods'}, :html=>{:class=> "food"} do |form| %>

  <div class="row">
    <div class="input">
      <%= form.text_field :name, placeholder: 'Name', autocomplete: 'off' %>
    </div>
    <div class="input">
      <%= form.text_field :cal, min: '0', placeholder: 'Calories' %>
    </div>
  </div>

  <div class="row">
    <div class="input">
      <%= form.text_field :protein, placeholder: 'Protein' %>
    </div>

    <div class="input">
      <%= form.text_field :carbohydrates, placeholder: 'Carbs' %>
    </div>

    <div class="input">
      <%= form.text_field :fat, placeholder: 'Fats'  %>
    </div>
  </div>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.submit :+, id: 'add-btn', class: 'btn-circle' %> 
  
<% end %>

app/views/foods/new.html.erb
<%= render 'form'%>

app/views/goals/_form.html.erb
<%= form_for [current_user, @goal], method: :patch, :html=>{:class=> "goal"} do |form| %>

  <div class="input">
    <h4>Calories</h4>
    <%= form.number_field :cal, min: '0', placeholder: 'Calories' %>
  </div>

  <div class="input">
    <h4>Protein</h4>
    <%= form.number_field :protein, min: '0', max: '999', placeholder: 'Protein' %>
  </div>

  <div class="input">
    <h4>Carbs</h4>
    <%= form.number_field :carbohydrates, min: '0', max: '999', placeholder: 'Carbs' %>
  </div>

  <div class="input">
    <h4>Fats</h4>
    <%= form.number_field :fat, min: '0', max: '999', placeholder: 'Fats' %>
  </div>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.submit 'Update Goal', id: 'save-btn' %> 
  
<% end %>

app/views/goals/_goal.html.erb
<%# add goals here with button and JS to toggle goals and edit goals %>

app/views/home/index.html.erb
<section id="home">
    <div class="card summary">
        <div class="card-header">
            <span>Protein <%= format_protein(@foods, @goal) %> (g)</span>
            <span>Carbohydrates <%= format_carbs(@foods, @goal) %> (g)</span>
            <span>Fats <%= format_fat(@foods, @goal) %> (g)</span>
        </div>        
        <div class="spacer"></div>
        <div class="card-body">
            <span>Calories <%= total_calories(@foods) %> cal</span>
            <span><%= calories_left(@foods, @goal) %> Calories Left </span>
        </div>
    </div>

    <div class="card add">
        <div class="card-header">
        </div>
        <div class="spacer"></div>
        <%= render 'foods/form'%>
    </div>

    <div class="spacer"></div>

    <div class="list">
        <% if no_food?(@foods) %>
            <p class="text-centered">No Food Logged</p>
            <%= image_tag 'hungry.gif', :id => 'hungry' %>
            <p class="text-centered">Go eat something!</p>
        <% else %>
            <table>
                <tr>
                    <th></th>
                    <th style="width: 90px">Cal</th>
                    <th style="width: 90px">Protein</th>
                    <th style="width: 90px">Carb</th>
                    <th style="width: 90px">Fats</th>
                    <th></th>
                </tr>   
                <tr class="spacer"></tr>
            <% @foods.each do |food| %>
                <tr class="food-chip">
                    <td><%= titleize(food.name) %></td>
                    <td><%= food.cal %> cal</td>
                    <td><%= food.protein %> g</td>
                    <td><%= food.carbohydrates %> g</td>
                    <td><%= food.fat %> g</td>
                    <td class="delete"><%= button_to "✕", food_path(id: food.id), method: :delete, class: 'btn-circle' %></td>
                </tr>
                <tr class="spacer"></tr>
            <% end %>
            </table>
        <% end %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nutrition Tracker</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'shared', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= render "shared/flash_snackbar"%>
  </body>

  <% if user_signed_in? %>
    <%= render "shared/footer" %>
    <%= render "shared/modal" %> <%# try out render partial here%>
  <% end %>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'shared', 'data-turbolinks-track' => true %>
</head>

  <body class="devise">
    <div class="card view-container">
      <%= yield %>
    </div>
    <div class="">
      <%= render "devise/shared/links" %>
    </div>

    <%= render "shared/flash_snackbar"%>
  </body>

</html>

app/views/shared/_flash_snackbar.erb
<% flash.each do |key, value| %>
  <div class="alert">
    <% if value.kind_of?(Array) %>
      <ul>
        <% value.each do |val| %>
          <li><%= val%></li>
        <% end %>
      </ul>  
    <% else %>
      <%= value %>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="sticky-footer" class="collapsed">
    <div id="settings-banner" class="hidden"></div>
    <div class="footer-content">
        <button id="profile-btn" class="btn-circle"></button>
        <%= button_to('Logout', destroy_user_session_path, method: :delete, class: 'btn', id: 'logout-btn') %>
    </div> 
    <div id="settings-content" class="hidden">
        <h3>Your Goals</h3>
        <%= render "goals/form" %> <%# try out render partial here%>
    </div>
</footer>

app/views/shared/_modal.html.erb
<div id="modal" class="hidden"> <!-- change hidden to click through and change home.js to reenable modal -->
    <div id="modal-backdrop"></div>
    <div id="modal-content" class="card">
        <%= button_tag '✕', 
            type: 'button', 
            onclick: '$("#modal").fadeOut("fast");
                      $("#modal").addClass("click-through");', 
            id: 'modal-close',
            class: 'btn-circle' %>
    </div>
<div>